# Generated by Django 3.0.4 on 2020-07-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(max_length=200)),
                ('mid', models.CharField(max_length=50)),
                ('bug', models.CharField(max_length=50)),
                ('procedure', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('progress_delta', models.CharField(max_length=50)),
                ('hours_delta', models.CharField(max_length=50)),
                ('modified_at', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartshow.Owner')),
            ],
        ),
    ]
