# Generated by Django 3.0.4 on 2020-07-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartshow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worklist',
            name='id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='row_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
