# Generated by Django 3.0.4 on 2020-07-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartshow', '0003_auto_20200707_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='bug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
