# Generated by Django 3.0.4 on 2020-07-08 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chartshow', '0004_auto_20200707_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='pre_date',
            field=models.DateField(default=20200709),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worklist',
            name='this_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
